### ISSUE TITLE
关于部署的一个问题

### ISSUE THREAD

**Issue by Cheng0x** [HeRaNO/xcpc-team-reg#1]
大大你好，我给您Github上留的邮箱（heran55@126.com）发送了一篇邮件，有时间希望可以回复一下，thx

**Comment by HeRaNO** [comment]
从报错上看应该是没有连接到数据库，可以试着直接在 shell 登录数据库看看是否有问题。

因为这个后端写得比较潦草，是为了学校校赛而赶工出来的，所以有些问题原因比较复杂，可能需要直接在生产环境调试代码才能知道具体是哪里有问题。

Good luck.
